# Import danych

Import funkcji z pliku [api_request.py](api_request.py)

In [25]:
import pandas as pd
from api_request import stations, api_request

In [26]:
df_stations = stations()
id_stations = df_stations["Identyfikator stacji"].unique().tolist() # lista z id stacji, potrzebne do innych url API

Trwa ładowanie danych z API do DataFrame...

Poprawno załadowano dane ✅

### Stanowiska pomiarowe

lista stanowisk pomiarowych dostępnych na wybranej stacji pomiarowej

In [27]:
df_sensors = api_request("station/sensors/", id_stations, "Lista stanowisk pomiarowych dla podanej stacji") 
id_sensors = df_sensors["Identyfikator stanowiska"].unique().tolist() # lista z id stanowisk, potrzebne do innych url API

Trwa ładowanie danych z API do DataFrame...

Wszystkie wartości dla 'Lista stanowisk pomiarowych dla podanej stacji' zostały załadowane ✅

### Dane pomiarowe 

dane pomiarowe na podstawie podanego identyfikatora stanowiska pomiarowego

In [28]:
df_measures = api_request("data/getData/", id_sensors, "Lista danych pomiarowych", item_id = "id_stacji", add_id=True)

Trwa ładowanie danych z API do DataFrame...

Nie udało się połączyć z API dla 'Lista danych pomiarowych'. 66 z 0 wszystkich wartości nie dodano do DataFrame ❌

### Indeks jakości powietrza

indeksy jakości powietrza na podstawie podanego identyfikatora stacji pomiarowej

In [29]:
df_air = api_request("aqindex/getIndex/", id_stations, "AqIndex")

Trwa ładowanie danych z API do DataFrame...

Wszystkie wartości dla 'AqIndex' zostały załadowane ✅

# 📊 Przegląd danych

### Stacje pomiarowe

In [ ]:
print(f"\nLiczba wierszy w df_stations: {len(df_stations)}\n")

20

In [31]:
df_stations.sample(5)

,Identyfikator stacji,Kod stacji,Nazwa stacji,WGS84 φ N,WGS84 λ E,Identyfikator miasta,Nazwa miasta,Gmina,Powiat,Województwo,Ulica
8,93,DsSzczaKolej,"Szczawno-Zdrój, ul. Kolejowa",50.804189,16.254111,915,Szczawno-Zdrój,Szczawno-Zdrój,wałbrzyski,DOLNOŚLĄSKIE,ul. Kolejowa 14
16,142,KpGrudPilsud,"Grudziądz, ul. Piłsudskiego",53.493550,18.762139,269,Grudziądz,Grudziądz,Grudziądz,KUJAWSKO-POMORSKIE,ul. Piłsudskiego 51
7,77,DsPolKasztan,"Polkowice, ul. Kasztanowa",51.502370,16.075051,721,Polkowice,Polkowice,polkowicki,DOLNOŚLĄSKIE,ul. Kasztanowa 29
4,70,DsOlawZolnAK,"Oława, ul. Żołnierzy Armii Krajowej",50.942073,17.291333,642,Oława,Oława,oławski,DOLNOŚLĄSKIE,ul. Żołnierzy AK 9
10,114,DsWrocBartni,"Wrocław, ul. Bartnicza",51.115933,17.141125,1064,Wrocław,Wrocław,Wrocław,DOLNOŚLĄSKIE,ul. Bartnicza

### Stanowiska pomiarowe

In [ ]:
print(f"\nLiczba wierszy w df_sensors: {len(df_sensors)}\n")

123

In [33]:
df_sensors.sample(5)

,Identyfikator stanowiska,Identyfikator stacji,Wskaźnik,Wskaźnik - wzór,Wskaźnik - kod,Id wskaźnika
78,32600,109,pył zawieszony PM2.5,PM2.5,PM2.5,69
7,221,38,dwutlenek azotu,NO2,NO2,6
97,665,117,dwutlenek azotu,NO2,NO2,6
36,411,74,arsen (całk. depozycja),As(cdepoz),As(cdepoz),82
74,618,109,pył zawieszony PM10,PM10,PM10,3

### Dane pomiarowe

In [ ]:
print(f"\nLiczba wierszy w df_measures: {len(df_measures)}\n")

1140

In [36]:
df_measures.sample(5)

,Kod stanowiska,Data,Wartość,id_stacji,data_dodania
949,DsWrocAlWisn-NO-1g,2026-05-30 07:00:00,39.1,739,2026-05-30 16:02:18.737198
1056,KpGrudPilsud-NO2-1g,2026-05-30 00:00:00,22.2,809,2026-05-30 16:02:19.074413
73,DsCzerStraza-O3-1g,2026-05-30 03:00:00,120.3,52,2026-05-30 16:02:10.125774
476,DsOlawZolnAK-PM10-1g,2026-05-30 00:00:00,25.1,400,2026-05-30 16:02:15.088020
18,DsCzerStraza-NO-1g,2026-05-29 22:00:00,0.5,49,2026-05-30 16:02:09.669719

In [37]:
df_measures.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1140 entries, 0 to 1139
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Kod stanowiska  1140 non-null   object
 1   Data            1140 non-null   object
 2   Wartość         1065 non-null   float64
 3   id_stacji       1140 non-null   int64
 4   data_dodania    1140 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 44.7+ KB

### Indeks jakości powietrza

In [ ]:
print(f"\nLiczba wierszy w df_air: {len(df_air)}\n")

20

In [39]:
df_air.sample(5)

,Identyfikator stacji pomiarowej,Data wykonania obliczeń indeksu,Wartość indeksu,Nazwa kategorii indeksu,"Data danych źródłowych, z których policzono wartość indeksu dla wskaźnika st",Data wykonania obliczeń indeksu dla wskaźnika SO2,Wartość indeksu dla wskaźnika SO2,Nazwa kategorii indeksu dla wskażnika SO2,"Data danych źródłowych, z których policzono wartość indeksu dla wskaźnika SO2",Data wykonania obliczeń indeksu dla wskaźnika NO2,...,Data wykonania obliczeń indeksu dla wskaźnika PM2.5,Wartość indeksu dla wskaźnika PM2.5,Nazwa kategorii indeksu dla wskażnika PM2.5,"Data danych źródłowych, z których policzono wartość indeksu dla wskaźnika PM2.5",Data wykonania obliczeń indeksu dla wskaźnika O3,Wartość indeksu dla wskaźnika O3,Nazwa kategorii indeksu dla wskażnika O3,"Data danych źródłowych, z których policzono wartość indeksu dla wskaźnika O3",Status indeksu ogólnego dla stacji pomiarowej,Kod zanieczyszczenia krytycznego
1,16.0,2026-05-30 15:20:11,-1.0,Brak indeksu,2026-05-30 14:00:00,2026-05-30 15:20:11,NaN,None,None,2026-05-30 15:20:11,...,None,NaN,None,None,None,NaN,None,None,False,OZON
6,74.0,2026-05-30 15:20:11,1.0,Dobry,2026-05-30 15:00:00,2026-05-30 15:20:11,0.0,Bardzo dobry,2026-05-30 15:00:00,2026-05-30 15:20:11,...,2026-05-30 15:20:11,NaN,None,None,2026-05-30 15:20:11,1.0,Dobry,2026-05-30 15:00:00,True,OZON
18,145.0,2026-05-30 15:35:13,-1.0,Brak indeksu,2026-05-30 15:00:00,2026-05-30 15:35:13,NaN,None,None,2026-05-30 15:35:13,...,None,NaN,None,None,None,NaN,None,None,False,OZON
5,NaN,None,NaN,None,None,None,NaN,None,None,None,...,None,NaN,None,None,None,NaN,None,None,None,None
3,52.0,2026-05-30 15:20:11,1.0,Dobry,2026-05-30 15:00:00,2026-05-30 15:20:11,0.0,Bardzo dobry,2026-05-30 15:00:00,2026-05-30 15:20:11,...,2026-05-30 15:20:11,0.0,Bardzo dobry,2026-05-30 15:00:00,2026-05-30 15:20:11,1.0,Dobry,2026-05-30 15:00:00,True,OZON

## 🧹 Czyszczenie danych

In [ ]:
# zmiana nazw kolumn
df_stations.rename(columns={
    "WGS84 φ N": "Szerokość geograficzna (N)",
    "WGS84 λ E": "Długość geograficzna (E)"
}, inplace=True)

In [41]:
# zmiana nazw kolumn (kod wygenerowany przez czat GPT)

df_air = df_air.rename(columns={
    'Identyfikator stacji pomiarowej': 'id_stacji',
    'Data wykonania obliczeń indeksu': 'data_obliczenia',
    'Wartość indeksu': 'wartosc_indeksu',
    'Nazwa kategorii indeksu': 'kategoria_indeksu',

    'Data danych źródłowych, z których policzono wartość indeksu dla wskaźnika st': 'data_zrodlowa',

    'Data wykonania obliczeń indeksu dla wskaźnika SO2': 'so2_data_obliczenia',
    'Wartość indeksu dla wskaźnika SO2': 'so2_wartosc',
    'Nazwa kategorii indeksu dla wskażnika SO2': 'so2_kategoria',
    'Data danych źródłowych, z których policzono wartość indeksu dla wskaźnika SO2': 'so2_data_zrodlowa',

    'Data wykonania obliczeń indeksu dla wskaźnika NO2': 'no2_data_obliczenia',
    'Wartość indeksu dla wskaźnika NO2': 'no2_wartosc',
    'Nazwa kategorii indeksu dla wskażnika NO2': 'no2_kategoria',
    'Data danych źródłowych, z których policzono wartość indeksu dla wskaźnika NO2': 'no2_data_zrodlowa',

    'Data wykonania obliczeń indeksu dla wskaźnika PM10': 'pm10_data_obliczenia',
    'Wartość indeksu dla wskaźnika PM10': 'pm10_wartosc',
    'Nazwa kategorii indeksu dla wskażnika PM10': 'pm10_kategoria',
    'Data danych źródłowych, z których policzono wartość indeksu dla wskaźnika PM10': 'pm10_data_zrodlowa',

    'Data wykonania obliczeń indeksu dla wskaźnika PM2.5': 'pm25_data_obliczenia',
    'Wartość indeksu dla wskaźnika PM2.5': 'pm25_wartosc',
    'Nazwa kategorii indeksu dla wskażnika PM2.5': 'pm25_kategoria',
    'Data danych źródłowych, z których policzono wartość indeksu dla wskaźnika PM2.5': 'pm25_data_zrodlowa',

    'Data wykonania obliczeń indeksu dla wskaźnika O3': 'o3_data_obliczenia',
    'Wartość indeksu dla wskaźnika O3': 'o3_wartosc',
    'Nazwa kategorii indeksu dla wskażnika O3': 'o3_kategoria',
    'Data danych źródłowych, z których policzono wartość indeksu dla wskaźnika O3': 'o3_data_zrodlowa',

    'Status indeksu ogólnego dla stacji pomiarowej': 'status_stacji',
    'Kod zanieczyszczenia krytycznego': 'krytyczne_zanieczyszczenie'
})

In [42]:
# usuwanie ewentualnych pustych wierszy

df_stations.dropna(subset=["Identyfikator stacji"], inplace=True)
df_sensors.dropna(subset=["Identyfikator stanowiska", "Identyfikator stacji"], inplace=True) 
df_measures.dropna(subset=["Kod stanowiska"], inplace=True)
df_air.dropna(subset=["id_stacji"], inplace=True)

In [43]:
# usuwanie ewentualnych duplikatów

df_stations.drop_duplicates(inplace=True, subset=["Identyfikator stacji"])
df_sensors.drop_duplicates(inplace=True, subset=["Identyfikator stanowiska", "Identyfikator stacji"])
df_measures.drop_duplicates(inplace=True, subset=["Kod stanowiska", "Data"])
df_air.drop_duplicates(inplace=True, subset=["id_stacji", "data_obliczenia"])

In [44]:
# usuwanie drukowanych liter
df_stations["Województwo"] = df_stations["Województwo"].str.capitalize()

In [45]:
df_stations.sample(3)

,Identyfikator stacji,Kod stacji,Nazwa stacji,Szerokość geograficzna (N),Długość geograficzna (N),Identyfikator miasta,Nazwa miasta,Gmina,Powiat,Województwo,Ulica
9,109,DsWalbrzWyso,"Wałbrzych, ul. Wysockiego",50.768729,16.269677,998,Wałbrzych,Wałbrzych,Wałbrzych,Dolnośląskie,ul. Wysockiego 11
0,11,DsCzerStraza,Czerniawa,50.912475,15.312190,142,Czerniawa,Świeradów-Zdrój,lubański,Dolnośląskie,ul. Strażacka 7
12,117,DsWrocWybCon,"Wrocław, wyb. Conrada-Korzeniowskiego",51.129378,17.029250,1064,Wrocław,Wrocław,Wrocław,Dolnośląskie,ul. Wyb. J.Conrada-Korzeniowskiego 18

In [46]:
# konwersja wartości float na int

df_air["id_stacji"] = df_air["id_stacji"].astype(int)

cols = ["wartosc_indeksu", "so2_wartosc", "no2_wartosc", "pm10_wartosc", "pm25_wartosc", "o3_wartosc"]

df_air[cols] = df_air[cols].astype("Int64")

In [47]:
df_air.sample(3)

,id_stacji,data_obliczenia,wartosc_indeksu,kategoria_indeksu,data_zrodlowa,so2_data_obliczenia,so2_wartosc,so2_kategoria,so2_data_zrodlowa,no2_data_obliczenia,...,pm25_data_obliczenia,pm25_wartosc,pm25_kategoria,pm25_data_zrodlowa,o3_data_obliczenia,o3_wartosc,o3_kategoria,o3_data_zrodlowa,status_stacji,krytyczne_zanieczyszczenie
9,109,2026-05-30 15:20:11,1,Dobry,2026-05-30 15:00:00,2026-05-30 15:20:11,0,Bardzo dobry,2026-05-30 15:00:00,2026-05-30 15:20:11,...,2026-05-30 15:20:11,0,Bardzo dobry,2026-05-30 15:00:00,2026-05-30 15:20:11,1,Dobry,2026-05-30 15:00:00,True,OZON
17,143,2026-05-30 15:35:13,-1,Brak indeksu,2026-05-30 15:00:00,2026-05-30 15:35:13,<NA>,None,None,2026-05-30 15:35:13,...,None,<NA>,None,None,None,<NA>,None,None,False,OZON
0,11,2026-05-30 15:20:11,1,Dobry,2026-05-30 15:00:00,2026-05-30 15:20:11,<NA>,None,None,2026-05-30 15:20:11,...,None,<NA>,None,None,2026-05-30 15:20:11,1,Dobry,2026-05-30 15:00:00,True,OZON