# Import danych

Import funkcji z pliku [api_request.py](api_request.py)

In [1]:
import pandas as pd
from api_request import stations, api_request

In [2]:
df_stations = stations()
id_stations = df_stations["Identyfikator stacji"].unique().tolist() # lista z id stacji, potrzebne do innych url API

Trwa ładowanie danych z API do DataFrame...

Poprawno załadowano dane ✅

### Stanowiska pomiarowe

lista stanowisk pomiarowych dostępnych na wybranej stacji pomiarowej

In [3]:
df_sensors = api_request("station/sensors/", id_stations, "Lista stanowisk pomiarowych dla podanej stacji") 
id_sensors = df_sensors["Identyfikator stanowiska"].unique().tolist() # lista z id stanowisk, potrzebne do innych url API

Trwa ładowanie danych z API do DataFrame...

Wszystkie wartości dla 'Lista stanowisk pomiarowych dla podanej stacji' zostały załadowane ✅

### Dane pomiarowe 

dane pomiarowe na podstawie podanego identyfikatora stanowiska pomiarowego

In [4]:
df_measures = api_request("data/getData/", id_sensors, "Lista danych pomiarowych", item_id = "id_stacji", add_id=True)

Trwa ładowanie danych z API do DataFrame...

Nie udało się połączyć z API dla 'Lista danych pomiarowych'. 66 z 0 wszystkich wartości nie dodano do DataFrame ❌

### Indeks jakości powietrza

indeksy jakości powietrza na podstawie podanego identyfikatora stacji pomiarowej

In [5]:
df_air = api_request("aqindex/getIndex/", id_stations, "AqIndex")

Trwa ładowanie danych z API do DataFrame...

Wszystkie wartości dla 'AqIndex' zostały załadowane ✅

# 📊 Przegląd danych

### Stacje pomiarowe

In [6]:
len(df_stations)

20

In [7]:
df_stations.sample(5)

,Identyfikator stacji,Kod stacji,Nazwa stacji,WGS84 φ N,WGS84 λ E,Identyfikator miasta,Nazwa miasta,Gmina,Powiat,Województwo,Ulica
18,145,KpToruWSikor,"Toruń, ul. Wały gen. Sikorskiego",53.012475,18.605681,966,Toruń,Toruń,Toruń,KUJAWSKO-POMORSKIE,ul. Wały gen. Sikorskiego 12
2,38,DsKlodzSzkol,"Kłodzko, ul. Szkolna",50.433493,16.653660,368,Kłodzko,Kłodzko,kłodzki,DOLNOŚLĄSKIE,ul. Szkolna 8
16,142,KpGrudPilsud,"Grudziądz, ul. Piłsudskiego",53.493550,18.762139,269,Grudziądz,Grudziądz,Grudziądz,KUJAWSKO-POMORSKIE,ul. Piłsudskiego 51
3,52,DsLegAlRzecz,"Legnica, Al. Rzeczypospolitej",51.204503,16.180513,453,Legnica,Legnica,Legnica,DOLNOŚLĄSKIE,Al. Rzeczypospolitej 10/12
12,117,DsWrocWybCon,"Wrocław, wyb. Conrada-Korzeniowskiego",51.129378,17.029250,1064,Wrocław,Wrocław,Wrocław,DOLNOŚLĄSKIE,ul. Wyb. J.Conrada-Korzeniowskiego 18

### Stanowiska pomiarowe

In [8]:
len(df_sensors)

123

In [9]:
df_sensors.sample(5)

,Identyfikator stanowiska,Identyfikator stacji,Wskaźnik,Wskaźnik - wzór,Wskaźnik - kod,Id wskaźnika
76,620,109,pył zawieszony PM2.5,PM2.5,PM2.5,69
26,388,70,benzo(a)piren w PM10,BaP(PM10),BaP(PM10),61
23,297,52,dwutlenek siarki,SO2,SO2,1
104,692,122,benzo(a)piren w PM10,BaP(PM10),BaP(PM10),61
57,460,77,benzo(a)piren w PM10,BaP(PM10),BaP(PM10),61

### Dane pomiarowe

In [10]:
len(df_measures)

1140

In [11]:
df_measures.sample(5)

,Kod stanowiska,Data,Wartość,id_stacji,data_dodania
540,DsWalbrzWyso-NO-1g,2026-05-30 13:00:00,0.90,613,2026-05-30 13:28:04.122325
1082,KpGrudPilsud-PM10-1g,2026-05-30 11:00:00,31.60,812,2026-05-30 13:28:06.028547
1018,DsWrocAlWisn-PM2.5-1g,2026-05-29 19:00:00,6.20,744,2026-05-30 13:28:05.784981
243,DsLegAlRzecz-C6H6-1g,2026-05-30 10:00:00,0.16,282,2026-05-30 13:28:01.738181
788,DsWrocWybCon-CO-1g,2026-05-30 05:00:00,216.00,660,2026-05-30 13:28:05.109357

In [12]:
df_measures.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1140 entries, 0 to 1139
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Kod stanowiska  1140 non-null   object
 1   Data            1140 non-null   object
 2   Wartość         1112 non-null   float64
 3   id_stacji       1140 non-null   int64
 4   data_dodania    1140 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 44.7+ KB

### Indeks jakości powietrza

In [13]:
len(df_air)

20

In [14]:
df_air.sample(5)

,Identyfikator stacji pomiarowej,Data wykonania obliczeń indeksu,Wartość indeksu,Nazwa kategorii indeksu,"Data danych źródłowych, z których policzono wartość indeksu dla wskaźnika st",Data wykonania obliczeń indeksu dla wskaźnika SO2,Wartość indeksu dla wskaźnika SO2,Nazwa kategorii indeksu dla wskażnika SO2,"Data danych źródłowych, z których policzono wartość indeksu dla wskaźnika SO2",Data wykonania obliczeń indeksu dla wskaźnika NO2,...,Data wykonania obliczeń indeksu dla wskaźnika PM2.5,Wartość indeksu dla wskaźnika PM2.5,Nazwa kategorii indeksu dla wskażnika PM2.5,"Data danych źródłowych, z których policzono wartość indeksu dla wskaźnika PM2.5",Data wykonania obliczeń indeksu dla wskaźnika O3,Wartość indeksu dla wskaźnika O3,Nazwa kategorii indeksu dla wskażnika O3,"Data danych źródłowych, z których policzono wartość indeksu dla wskaźnika O3",Status indeksu ogólnego dla stacji pomiarowej,Kod zanieczyszczenia krytycznego
0,11.0,2026-05-30 13:20:14,1.0,Dobry,2026-05-30 13:00:00,2026-05-30 13:20:14,NaN,None,None,2026-05-30 13:20:14,...,None,NaN,None,None,2026-05-30 13:20:14,1.0,Dobry,2026-05-30 13:00:00,True,OZON
5,NaN,None,NaN,None,None,None,NaN,None,None,None,...,None,NaN,None,None,None,NaN,None,None,None,None
18,145.0,2026-05-30 13:15:14,1.0,Dobry,2026-05-30 13:00:00,2026-05-30 13:15:14,NaN,None,None,2026-05-30 13:15:14,...,None,NaN,None,None,None,NaN,None,None,True,OZON
10,114.0,2026-05-30 13:20:14,1.0,Dobry,2026-05-30 13:00:00,None,NaN,None,None,2026-05-30 13:20:14,...,None,NaN,None,None,2026-05-30 13:20:14,1.0,Dobry,2026-05-30 13:00:00,True,OZON
9,109.0,2026-05-30 13:20:14,1.0,Dobry,2026-05-30 13:00:00,2026-05-30 13:20:14,0.0,Bardzo dobry,2026-05-30 13:00:00,2026-05-30 13:20:14,...,2026-05-30 13:20:14,0.0,Bardzo dobry,2026-05-30 13:00:00,2026-05-30 13:20:14,1.0,Dobry,2026-05-30 13:00:00,True,OZON

## 🧹 Czyszczenie danych

In [15]:
# zmiana nazw kolumn
df_stations.rename(columns={
    "WGS84 φ N": "Szerokość geograficzna (N)",
    "WGS84 λ E": "Długość geograficzna (N)"
}, inplace=True)

In [16]:
# zmiana nazw kolumn (kod wygenerowany przez czat GPT)

df_air = df_air.rename(columns={
    'Identyfikator stacji pomiarowej': 'id_stacji',
    'Data wykonania obliczeń indeksu': 'data_obliczenia',
    'Wartość indeksu': 'wartosc_indeksu',
    'Nazwa kategorii indeksu': 'kategoria_indeksu',

    'Data danych źródłowych, z których policzono wartość indeksu dla wskaźnika st': 'data_zrodlowa',

    'Data wykonania obliczeń indeksu dla wskaźnika SO2': 'so2_data_obliczenia',
    'Wartość indeksu dla wskaźnika SO2': 'so2_wartosc',
    'Nazwa kategorii indeksu dla wskażnika SO2': 'so2_kategoria',
    'Data danych źródłowych, z których policzono wartość indeksu dla wskaźnika SO2': 'so2_data_zrodlowa',

    'Data wykonania obliczeń indeksu dla wskaźnika NO2': 'no2_data_obliczenia',
    'Wartość indeksu dla wskaźnika NO2': 'no2_wartosc',
    'Nazwa kategorii indeksu dla wskażnika NO2': 'no2_kategoria',
    'Data danych źródłowych, z których policzono wartość indeksu dla wskaźnika NO2': 'no2_data_zrodlowa',

    'Data wykonania obliczeń indeksu dla wskaźnika PM10': 'pm10_data_obliczenia',
    'Wartość indeksu dla wskaźnika PM10': 'pm10_wartosc',
    'Nazwa kategorii indeksu dla wskażnika PM10': 'pm10_kategoria',
    'Data danych źródłowych, z których policzono wartość indeksu dla wskaźnika PM10': 'pm10_data_zrodlowa',

    'Data wykonania obliczeń indeksu dla wskaźnika PM2.5': 'pm25_data_obliczenia',
    'Wartość indeksu dla wskaźnika PM2.5': 'pm25_wartosc',
    'Nazwa kategorii indeksu dla wskażnika PM2.5': 'pm25_kategoria',
    'Data danych źródłowych, z których policzono wartość indeksu dla wskaźnika PM2.5': 'pm25_data_zrodlowa',

    'Data wykonania obliczeń indeksu dla wskaźnika O3': 'o3_data_obliczenia',
    'Wartość indeksu dla wskaźnika O3': 'o3_wartosc',
    'Nazwa kategorii indeksu dla wskażnika O3': 'o3_kategoria',
    'Data danych źródłowych, z których policzono wartość indeksu dla wskaźnika O3': 'o3_data_zrodlowa',

    'Status indeksu ogólnego dla stacji pomiarowej': 'status_stacji',
    'Kod zanieczyszczenia krytycznego': 'krytyczne_zanieczyszczenie'
})

In [17]:
# usuwanie ewentualnych pustych wierszy

df_stations.dropna(subset=["Identyfikator stacji"], inplace=True)
df_sensors.dropna(subset=["Identyfikator stanowiska", "Identyfikator stacji"], inplace=True) 
df_measures.dropna(subset=["Kod stanowiska"], inplace=True)
df_air.dropna(subset=["id_stacji"], inplace=True)

In [18]:
# usuwanie ewentualnych duplikatów

df_stations.drop_duplicates(inplace=True, subset=["Identyfikator stacji"])
df_sensors.drop_duplicates(inplace=True, subset=["Identyfikator stanowiska", "Identyfikator stacji"])
df_measures.drop_duplicates(inplace=True, subset=["Kod stanowiska", "Data"])
df_air.drop_duplicates(inplace=True, subset=["id_stacji", "data_obliczenia"])

In [19]:
# usuwanie drukowanych liter
df_stations["Województwo"] = df_stations["Województwo"].str.capitalize()

In [20]:
df_stations.sample(3)

,Identyfikator stacji,Kod stacji,Nazwa stacji,Szerokość geograficzna (N),Długość geograficzna (N),Identyfikator miasta,Nazwa miasta,Gmina,Powiat,Województwo,Ulica
16,142,KpGrudPilsud,"Grudziądz, ul. Piłsudskiego",53.493550,18.762139,269,Grudziądz,Grudziądz,Grudziądz,Kujawsko-pomorskie,ul. Piłsudskiego 51
10,114,DsWrocBartni,"Wrocław, ul. Bartnicza",51.115933,17.141125,1064,Wrocław,Wrocław,Wrocław,Dolnośląskie,ul. Bartnicza
19,150,KpBydFieldor,"Bydgoszcz, ul. Fieldorfa",53.151452,18.132062,90,Bydgoszcz,Bydgoszcz,Bydgoszcz,Kujawsko-pomorskie,ul. gen. Augusta Emila Fieldorfa „Nila” 13

In [21]:
# konwersja wartości float na int

df_air["id_stacji"] = df_air["id_stacji"].astype(int)

cols = ["wartosc_indeksu", "so2_wartosc", "no2_wartosc", "pm10_wartosc", "pm25_wartosc", "o3_wartosc"]

df_air[cols] = df_air[cols].astype("Int64")

In [22]:
df_air.sample(3)

,id_stacji,data_obliczenia,wartosc_indeksu,kategoria_indeksu,data_zrodlowa,so2_data_obliczenia,so2_wartosc,so2_kategoria,so2_data_zrodlowa,no2_data_obliczenia,...,pm25_data_obliczenia,pm25_wartosc,pm25_kategoria,pm25_data_zrodlowa,o3_data_obliczenia,o3_wartosc,o3_kategoria,o3_data_zrodlowa,status_stacji,krytyczne_zanieczyszczenie
10,114,2026-05-30 13:20:14,1,Dobry,2026-05-30 13:00:00,None,<NA>,None,None,2026-05-30 13:20:14,...,None,<NA>,None,None,2026-05-30 13:20:14,1,Dobry,2026-05-30 13:00:00,True,OZON
3,52,2026-05-30 13:20:14,1,Dobry,2026-05-30 13:00:00,2026-05-30 13:20:14,0,Bardzo dobry,2026-05-30 13:00:00,2026-05-30 13:20:14,...,2026-05-30 13:20:14,0,Bardzo dobry,2026-05-30 13:00:00,2026-05-30 13:20:14,1,Dobry,2026-05-30 13:00:00,True,OZON
9,109,2026-05-30 13:20:14,1,Dobry,2026-05-30 13:00:00,2026-05-30 13:20:14,0,Bardzo dobry,2026-05-30 13:00:00,2026-05-30 13:20:14,...,2026-05-30 13:20:14,0,Bardzo dobry,2026-05-30 13:00:00,2026-05-30 13:20:14,1,Dobry,2026-05-30 13:00:00,True,OZON

In [24]:
# df_measures.to_csv(r"C:\Users\Mateusz\Desktop\ZBIORCZE\TECH\ANALIZA DANYCH\Z_inne\Analiza_jakosci_powietrza\data.csv", index = False)